<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-M9MJF76J" failures="0" tests="2" name="com.supermarket.tests.UserTest" time="8.605" errors="1" timestamp="2023-01-19T12:28:40 IST" skipped="0">
  <testcase classname="com.supermarket.tests.UserTest" name="search" time="8.139">
    <error message="org/yaml/snakeyaml/Yaml" type="java.lang.NoClassDefFoundError">
      <![CDATA[java.lang.NoClassDefFoundError: org/yaml/snakeyaml/Yaml
at com.github.javafaker.service.FakeValues.loadValues(FakeValues.java:73)
at com.github.javafaker.service.FakeValues.get(FakeValues.java:49)
at com.github.javafaker.service.FakeValuesGrouping.get(FakeValuesGrouping.java:25)
at com.github.javafaker.service.FakeValuesService.fetchObject(FakeValuesService.java:193)
at com.github.javafaker.service.FakeValuesService.safeFetch(FakeValuesService.java:159)
at com.github.javafaker.service.FakeValuesService.resolve(FakeValuesService.java:305)
at com.github.javafaker.Name.name(Name.java:29)
at com.github.javafaker.Name.fullName(Name.java:54)
at com.supermarket.pages.Userpage.searchuser(Userpage.java:72)
at com.supermarket.tests.UserTest.search(UserTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.Yaml
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 36 more
]]>
    </error>
  </testcase> <!-- search -->
  <system-out/>
  <testcase classname="com.supermarket.tests.UserTest" name="passwordValidation" time="0.466"/>
  <system-out/>
</testsuite> <!-- com.supermarket.tests.UserTest -->
